version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - dev-network

volumes:
  node_modules:

networks:
  dev-network:
    driver: bridge 