name: Test Smart Docker Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-smart-docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout test repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Smart Docker Build Action
        uses: kengo-k/smart-docker-build@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timezone: 'Asia/Tokyo'