name: smart-docker-build demo

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smart-docker-build-demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test smart-docker-build action
      uses: kengo-k/smart-docker-build@main
      with:
        repository_token: ${{ secrets.GHCR_TOKEN }}
